config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  get 'account/login'
  get 'gallery/checkout'
  post 'gallery/search'
  get 'gallery/search'
  post 'gallery/checkout'
  get 'gallery/index'
  resources :stores
  get 'admin/login'
  get  '/admin/logout'
  post 'admin/login'
  devise_for :users
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  include ActiveMerchant::Billing
  def index
    @gallery = Store.all
  end
  	def checkout
    amount_to_charge = session[:amount].to_i
       if request.post?
        ActiveMerchant::Billing::Base.mode = :test
         # ActiveMerchant accepts all amounts as Integer values in cents    #amount = 100    
         credit_card = ActiveMerchant::Billing::CreditCard.new(
           :first_name => params[:first_name],
           :last_name => params[:last_name],
           :number => params[:credit_no].to_i,
           :month => params[:check][:month].to_i,
           :year => params[:check][:year].to_i,
           :verification_value => params[:verification_number].to_i
       )
           # Validating the card automatically detects the card type    
           gateway =ActiveMerchant::Billing::TrustCommerceGateway.new(
               :login => 'TestMerchant',
               :password =>'password',
               :test => 'true' 
           )
           response = gateway.authorize(amount_to_charge , credit_card)
           #response = gateway.purchase(amount_to_charge, credit_card)    
           puts response.inspect
           if response.success?
               gateway.capture(amount_to_charge, response.authorization)
               #UserNotifier.purchase_complete(session[:user],current_cart).deliver
               flash[:notice]="Thank You for using Yummy. The oreder details are sent to your mail"
               session[:cart_id]=nil
               session[:amount]=nil
               redirect_to '/gallery/purchase_complete'
           else 
               flash[:notice]= "Something went wrong.Try again"
               render :action => "checkout"
           end
       end
   end
   def search
    keyword = '%' + params[:search]+ '%'
    @gallery = Store.find_by_sql ["Select * from stores WHERE name like ? or category like ? or description like ?", keyword,keyword,keyword]
end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/_image_gallery.html.erb
<table>
<tr>
<% count=0 %>
<% @gallery.each do |gallery|%>
<% if (count % 3) == 0%>
</tr><tr>
<% end %>
<% count+=1 %>
<td><br>
<%# <%gallery.images.each do |image| %>
<%# <%=image_tag image.first, :width=>"200px", :height=>"200px" %>
<%# <% end %>
<% if gallery.images.attached? %>
<%= image_tag gallery.images.first, style:'width:250px; height: 250px'%>
<% end %>
<br><br>
<%= gallery.name %>
<br />Price : ₹<%= gallery.price %>
<br />Description: <%= gallery.Description %>
<br />Category: <%= gallery.category %><br><br>
 <%= button_to 'Add to cart',line_items_path(:store_id => gallery.id)%> 
 <%# <%= button_to 'Show', store_path %>  %>
 </td>
 <% end %>
 </tr>
 </table>
 <br>

app/views/gallery/checkout.html.erb
<%= flash[:notice]%><br />
    <div class="outer">
      <div class="cent">  
        <h3>Total Amount to paid : <%= number_to_currency(session[:amount]) %></h3>
        
		<%= form_with url: "/gallery/checkout", method: :post do |f| %>

          <div class="field">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name %>
          </div>
          <div class="field">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name %>
          </div>
          <div class="field">
            <%= f.label :credit_card_no %><br />
            <%= f.text_field :credit_no %>
          </div>
          <div class="field">
            <%= f.label :date_of_expiry %><br />
              <select name="check[month]" id="check_out_month">
                <option selected value="01">Janurary 
                <option  value="02">Feburary
                <option  value="03">March
                <option  value="04">April 
                <option  value="05">May 
                <option  value="06">June 
                <option  value="07">July 
                <option  value="08">August 
                <option  value="09">September 
                <option  value="10">October 
                <option  value="11">November 
                <option  value="12">December 
              </select>
              <select name="check[year]" id=check_out_year">
                <option selected value="2022">2022
                <option  value="2023">2023
                <option  value="2024">2024
                <option  value="2025">2025
                <option  value="2026">2026
                <option  value="2027">2027
                <option  value="2028">2028
                <option  value="2029">2029
                <option  value="2030">2030
                <option  value="2031">2031
                <option  value="2032">2032
                <option  value="2033">2033
            </select>
          </div>

          <div class="field">
            <%= f.label :verification_number %><br />
            <%= f.text_field :verification_number %>
          </div>
          <br/><br/>
          <div class="actions">
            <button class="button"><%= f.submit "Submit"%></button>
          </div>
        <% end %>

app/views/gallery/index.html.erb
<div class="center_hello">
<%= render 'image_gallery'%>
<%# <img src="/assets/coffee.jpg" height="550px" width="100%"><br><br> %>
<%= form_for(:search,:url=>"/gallery/search") do |f| %>
    Search <input type="text" name="search">
    <input type="submit" class="btn btn-dark" value="Go">
<% end %><br/>

app/views/gallery/search.html.erb
<div class="center_hello">
Your search result is :
<%= render 'image_gallery'%>
</div>